const topUpEmmaAccount = async (constraint) => {
    //FUNC HERE WHICH WOULD TOP UP EMMA ACCOUNT WITH SHARES IN DESIRED PRICE RANGE, ASWELL AS FULFILL
    //ALL SHARES IN 'freeShareQueue' AS TIMED INTERVALS WHEN MARKET IS OPEN.
}