const topUpEmmaAccount = async (constraint) => {
    //FUNC HERE WHICH RUNS TO TOP UP THE EMMA ACCOUNT WITH ALL PRICE RANGES
    //CALLED EITHER WHEN THERE'S NO SHARES AVAILABLE WITHIN THE USERS SPECIFIED RANGE, OR ON A TIME INTERVAL
}